version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - videos_data:/app/storage/videos
      - .:/app  # Optional: Mount the entire project for development
    env_file:
      - .env
    restart: unless-stopped

volumes:
  videos_data:
    driver: local
